### ISSUE TITLE
Slumspawner error when user logged in  AttributeError: 'super' object has no attribute '_env_default'

### ISSUE THREAD

**Issue by jenarabi** [mkgilbert/slurmspawner#1]
Hi,
Before installing SlurmSpawner my JupyterHub was running fine without any issue.

Now after installing slurmspawner the following error found when a user trying to login the Hub UI.
deda1x1680:/sw-stdg/apps/Jupyterhub # /sw-stdg/apps/Jupyterhub/bin/jupyterhub -f jupyterhub_config.py
[I 2018-01-22 14:17:42.384 JupyterHub app:724] Loading cookie_secret from /sw-stdg/apps/Jupyterhub/jupyterhub_cookie_secret
[W 2018-01-22 14:17:42.416 JupyterHub app:365]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.

[W 2018-01-22 14:17:42.419 JupyterHub app:864] No admin users, admin interface will be unavailable.
[W 2018-01-22 14:17:42.419 JupyterHub app:865] Add any administrative users to `c.Authenticator.admin_users` in config.
[I 2018-01-22 14:17:42.419 JupyterHub app:892] Not using whitelist. Any authenticated user will be allowed.
[W 2018-01-22 14:17:42.431 JupyterHub app:1097] x179796 not running.
[I 2018-01-22 14:17:42.496 JupyterHub app:1453] Hub API listening on http://127.0.0.1:8081/hub/
[I 2018-01-22 14:17:42.499 JupyterHub app:1176] Starting proxy @ http://*:8000/
14:17:42.606 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
14:17:42.617 - info: [ConfigProxy] Proxying https://*:8000 to http://127.0.0.1:8081
14:17:42.617 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2018-01-22 14:17:42.703 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8000/
[I 2018-01-22 14:18:15.126 JupyterHub log:100] 302 GET / (@::1) 1.72ms
[I 2018-01-22 14:18:15.144 JupyterHub log:100] 302 GET /hub (@::1) 0.40ms
[I 2018-01-22 14:18:15.155 JupyterHub log:100] 302 GET /hub/ (@::1) 0.80ms
[I 2018-01-22 14:18:15.159 JupyterHub log:100] 302 GET /login (@::1) 0.52ms
[I 2018-01-22 14:18:15.187 JupyterHub log:100] 200 GET /hub/login (@::1) 23.01ms
[E 2018-01-22 14:18:25.953 JupyterHub user:251] Unhandled error starting x179796's server: 'super' object has no attribute '_env_default'
[E 2018-01-22 14:18:25.999 JupyterHub web:1590] Uncaught exception POST /hub/login?next= (::1)
    HTTPServerRequest(protocol='https', host='localhost:8000', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::1', headers={'X-Forwarded-Host': 'localhost:8000', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Port': '8000', 'X-Forwarded-For': '::1', 'Content-Length': '46', 'Content-Type': 'application/x-www-form-urlencoded', 'Upgrade-Insecure-Requests': '1', 'Connection': 'close', 'Dnt': '1', 'Cookie': '_xsrf=2|1bb1780d|cb28b75c9d271be5e536524df0811d6a|1515597964', 'Referer': 'https://localhost:8000/hub/login', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.5', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'Host': 'localhost:8000'})
    Traceback (most recent call last):
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/jupyterhub/handlers/login.py", line 84, in post
        yield self.spawn_single_user(user)
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 328, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), f)
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/jupyterhub/user.py", line 261, in spawn
        raise e
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/jupyterhub/user.py", line 229, in spawn
        ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/sw-stdg/apps/Jupyterhub/slurmspawner-master/slurmspawner/slurmspawner.py", line 380, in start
        env = self.env.copy()
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
        return self.get(obj, cls)
      File "/sw-stdg/apps/Jupyterhub/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
        value = self._validate(obj, dynamic_default())
      File "/sw-stdg/apps/Jupyterhub/slurmspawner-master/slurmspawner/slurmspawner.py", line 116, in _env_default
        env = super()._env_default()
    AttributeError: 'super' object has no attribute '_env_default'

[E 2018-01-22 14:18:26.012 JupyterHub log:99] {
      "X-Forwarded-Host": "localhost:8000",
      "X-Forwarded-Proto": "https",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::1",
      "Content-Length": "46",
      "Content-Type": "application/x-www-form-urlencoded",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Dnt": "1",
      "Cookie": "_xsrf=2|1bb1780d|cb28b75c9d271be5e536524df0811d6a|1515597964",
      "Referer": "https://localhost:8000/hub/login",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0",
      "Host": "localhost:8000"
    }
[E 2018-01-22 14:18:26.012 JupyterHub log:100] 500 POST /hub/login?next= (@::1) 730.53ms
14:22:42.741 - info: [ConfigProxy] 200 GET /api/routes
^C
Interrupted
[I 2018-01-22 14:25:14.920 JupyterHub app:1332] Cleaning up single-user servers...
[I 2018-01-22 14:25:15.128 JupyterHub app:1343] Cleaning up proxy[5040]...
[I 2018-01-22 14:25:15.129 JupyterHub app:1369] ...done

Need your help.
Thanks,
Rabindra

**Comment by mkgilbert** [comment]
Rabindra, could you post the output of `pip freeze` in the environment you're running in? It might help to see what versions of the various packages you're using. This repo hasn't been updated in a while, so the problem you're seeing could very well be due to something changing in one of the dependencies.

**Comment by rsearles35** [comment]
I'm actually having the same issue as @jenarabi. Has this been resolved?
